services:

  mongodb:
    image: mongo:7
    container_name: crud-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - crud-network

  backend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
      target: backend
    container_name: crud-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - crud-network

  frontend:
    build:
      context: ..
      dockerfile: Docker/Dockerfile
      target: frontend
    container_name: crud-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - crud-network

volumes:
  mongodb_data:

networks:
  crud-network:
    driver: bridge