pipeline {
    agent any

    environment {
        AWS_REGION     = 'ap-south-1'
        ECR_REPOSITORY = 'secure-n-tier-infra-dev'
        APP_TAG_NAME   = 'secure-n-tier-infra-dev-app'
        IMAGE_TAG      = "${BUILD_NUMBER}"
    }

    stages {

        stage('Docker Build') {
            steps {
                sh '''
                    docker build \
                    -f Docker/Dockerfile \
                    -t ${ECR_REPOSITORY}:${IMAGE_TAG} \
                    -t ${ECR_REPOSITORY}:latest \
                    .
                '''
            }
        }
        
        stage('Security Scan') {
            steps {
                sh '''
                trivy image \
                --ignore-unfixed \
                --severity HIGH,CRITICAL \
                ${ECR_REPOSITORY}:${IMAGE_TAG}
                '''
            }
        }

        stage('ECR Login') {
            steps {
                sh '''
                    AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
                    --query Account \
                    --output text)

                    ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                    aws ecr get-login-password \
                    --region ${AWS_REGION} | \
                    docker login \
                    --username AWS \
                    --password-stdin ${ECR_REGISTRY}
                '''
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                    AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
                    --query Account \
                    --output text)

                    ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

                    docker tag \
                    ${ECR_REPOSITORY}:${IMAGE_TAG} \
                    ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

                    docker tag \
                    ${ECR_REPOSITORY}:latest \
                    ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

                    docker push \
                    ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}

                    docker push \
                    ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest
                '''
            }
        }

       stage('Deploy to App Servers') {
    steps {
        sh '''
            AWS_ACCOUNT_ID=$(aws sts get-caller-identity \
            --query Account \
            --output text)

            ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

            MONGODB_PRIVATE_IP=$(aws ec2 describe-instances \
            --region ${AWS_REGION} \
            --filters "Name=tag:Name,Values=secure-n-tier-infra-dev-mongodb" \
            --query "Reservations[].Instances[?State.Name=='running'].PrivateIpAddress | [0]" \
            --output text)

            echo "MongoDB Private IP: ${MONGODB_PRIVATE_IP}"

            if [ -z "${MONGODB_PRIVATE_IP}" ] || [ "${MONGODB_PRIVATE_IP}" = "None" ]; then
                echo "ERROR: MongoDB private IP not found"
                exit 1
            fi

            MONGO_URI="mongodb://${MONGODB_PRIVATE_IP}:27017/crud"

            echo "Deploying with MongoDB URI: ${MONGO_URI}"

            aws ssm send-command \
            --region ${AWS_REGION} \
            --targets "Key=tag:Name,Values=${APP_TAG_NAME}" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy application ${IMAGE_TAG}" \
            --parameters "commands=[
              \"aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}\",
              \"docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest\",
              \"docker rm -f app || true\",
              \"docker run -d --name app --restart unless-stopped -p 3000:3000 -e MONGO_URI=${MONGO_URI} ${ECR_REGISTRY}/${ECR_REPOSITORY}:latest\"
            ]"
        '''
    }
}
    }

    post {
        success {
            echo 'CI/CD pipeline completed successfully.'
        }

        failure {
            echo 'CI/CD pipeline failed.'
        }

        always {
            sh 'docker image prune -f || true'
        }
    }
}